name: CI

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        pyspark-version: ["3.3.2", "3.4.0"]
        java-version: ["8", "11"]
        exclude:
          - python-version: "3.11"
            pyspark-version: "3.3.2"
            java-version: "8"
          - python-version: "3.11"
            pyspark-version: "3.3.2"
            java-version: "11"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt

      - name: Install pyspark
        run: pip install pyspark==${{ matrix.pyspark-version }}

      - name: Install test requirements
        run: pip install -r requirements-tests.txt

      - name: Install skspark
        run: pip install .

      - name: Run tests (pytest)
        run: pytest --disable-warnings -vv -rxXs python/test
